spring:
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: admin
    password: admin

  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none